#!/usr/bin/env bash
if [[ $# -eq 0 ]]; then
  echo "usage: todo<init|list|add|edit|remove|reset|mark|unmark> [args]"
fi

if [[ $1 == 'init' ]]; then
   mkdir -p "$HOME/.todo"
   touch "$HOME/.todo/tasks"
  echo "Initialized successfully."
fi

if [[ ! -f "$HOME/.todo/tasks" ]];then
   echo "please run 'todo init' before running '$1' command."
fi

if [[ $1=='list' ]]; then
   echo "# To be done"
   cat "$HOME/.todo/tasks"
   echo "# Completed"
   echo "# Empty"

fi
